# Generated by Django 5.2.8 on 2025-12-01 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeterias', '0003_cafeteria_operating_hours'),
        ('reviews', '0004_menu_restaurant_alter_review_menu_menu_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='restaurant',
        ),
        migrations.AlterField(
            model_name='review',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='cafeterias.menu'),
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at']},
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
