# Generated by Django 5.2.8 on 2025-11-18 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafeterias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafeteria',
            name='campus',
        ),
        migrations.RemoveField(
            model_name='cafeteria',
            name='close_time',
        ),
        migrations.RemoveField(
            model_name='cafeteria',
            name='open_time',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='image',
        ),
        migrations.DeleteModel(
            name='Campus',
        ),
    ]
