# Generated by Django 5.2.8 on 2025-11-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeterias', '0002_remove_cafeteria_campus_remove_cafeteria_close_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafeteria',
            name='operating_hours',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
