# Generated by Django 5.2.8 on 2025-12-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeterias', '0003_cafeteria_operating_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafeteria',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cafeterias/'),
        ),
        migrations.AddField(
            model_name='menu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menus/'),
        ),
    ]
