# Generated by Django 5.2.8 on 2025-12-02 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafeterias', '0005_cafeteria_image_menu_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafeteria',
            name='image',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='image',
        ),
    ]
