# Generated by Django 5.2.8 on 2025-12-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeterias', '0006_remove_cafeteria_image_remove_menu_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafeteria',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cafeteria_images/'),
        ),
        migrations.AddField(
            model_name='menu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_images/'),
        ),
    ]
